### ISSUE TITLE
"npm install auto-tunnel" does not work

### ISSUE THREAD

**Issue by mknj** [stevenvachon/auto-tunnel#1]

**Comment by stevenvachon** [comment]
npm log please

**Comment by stevenvachon** [comment]
This isn't released yet. For now, use
```shell
npm install stevenvachon/auto-tunnel
```

**Comment by stevenvachon** [comment]
At this point, though, there's probably no reason to release this library, as [proxy-agent](https://npmjs.com/proxy-agent) fulfills this library's goal.
